using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Serilog;

namespace Content.Client.Lobby.UI.Roles;

[GenerateTypedNameReferences]
public sealed partial class TraitPreferenceSelector : Control
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public int Cost;
    // Afterlight Start
    public string TraitId;
    // Afterlight End

    public bool Preference
    {
        get => Checkbox.Pressed;
        set => Checkbox.Pressed = value;
    }

    public event Action<bool>? PreferenceChanged;

    public TraitPreferenceSelector(TraitPrototype trait)
    {
        // Afterlight Start
        IoCManager.InjectDependencies(this);
        // Afterlight End
        RobustXamlLoader.Load(this);

        var text = trait.Cost != 0 ? $"[{trait.Cost}] " : "";
        text += Loc.GetString(trait.Name);

        Cost = trait.Cost;
        // Afterlight Start
        TraitId = trait.ID;
        // Afterlight End
        Checkbox.Text = text;
        Checkbox.OnToggled += OnCheckBoxToggled;

        if (trait.Description is { } desc)
        {
            // Afterlight Start
            // Add the trait's incompatibility info to the tooltip
            var finalDesc = Loc.GetString(desc);
            if (trait.IncompatibleWith.Length > 0)
            {
                var prefix = Loc.GetString("humanoid-profile-editor-trait-incompatible-prefix");
                finalDesc += "\n\n" + prefix;
            }
            foreach (var incompatibleTraitId in trait.IncompatibleWith)
            {
                if (!_prototypeManager.TryIndex<TraitPrototype>(incompatibleTraitId, out var incompatibleTraitPrototype))
                {
                    finalDesc += "TRAITNOTFOUND: " + incompatibleTraitId;
                    continue;
                }

                finalDesc += "\n" + Loc.GetString(incompatibleTraitPrototype.Name);
            }
            Checkbox.ToolTip = finalDesc;
            // Afterlight End
        }
    }

    private void OnCheckBoxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        PreferenceChanged?.Invoke(Preference);
    }
}
