// SPDX-FileCopyrightText: 2025 Starlight
// SPDX-License-Identifier: Starlight-MIT

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.UI.Systems.Characters.Controls;

[GenerateTypedNameReferences]
public sealed partial class CharacterOverviewControl : Control
{
    public CharacterOverviewControl()
    {
        RobustXamlLoader.Load(this);
    }
}