name: RSI Validator

on:
  push:
    branches: [ master, staging, stable, Starlight, main ]
  merge_group:
  pull_request:
    paths:
      - '**.rsi/**'

jobs:
  validate_rsis:
    name: Validate RSIs
    runs-on: self-hosted
    steps:
      - name: Install libraries
        run: |
          sudo apt-get update && sudo apt-get install -y python3.11 python3-pip
      - uses: actions/checkout@v4.2.2
      - name: Setup Submodule
        run: git submodule update --init
      - name: Pull engine updates
        uses: space-wizards/submodule-dependency@v0.1.5
      - name: Install Python dependencies
        run: |
          pip3 install --ignore-installed --user pillow jsonschema
      - name: Validate RSIs
        run: |
          python3 Tools/Schemas/validate_rsis.py Resources/
